# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'
menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link: 'https://www.facebook.com/MelanyeLainez/'}
- {icon: 'instagram', link: 'http://www.instagram.com/melanye_26/'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

